# Generated by Django 5.0.5 on 2024-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.IntegerField(max_length=3)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
