# Generated by Django 5.0.5 on 2024-05-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_course_availablity_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(max_length=15),
        ),
    ]
