# Generated by Django 5.0.5 on 2024-06-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy',
            new_name='Ticket',
        ),
    ]
